Rollback added

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,6 +45,11 @@ jobs:
                         RELEASE_DATE=$(date +%Y%m%d%H%M%S)
                         NEW_RELEASE_DIR="$PROJECT_ROOT/releases/$RELEASE_DATE"
 
+                        if [ -L "$PROJECT_ROOT/current" ]; then
+                            PREV_RELEASE_DIR=$(readlink -f "$PROJECT_ROOT/current")
+                        else
+                            PREV_RELEASE_DIR=""
+                        fi
 
                         # папка релиза
                         mkdir -p $NEW_RELEASE_DIR
@@ -59,7 +64,7 @@ jobs:
                             -w /app \
                             composer install --no-dev --prefer-dist --optimize-autoloader --ignore-platform-reqs
 
-                        echo "Trying migrations"
+                        # миграция с использованием старого phpnew, но новых файлов
                         cd $PROJECT_ROOT
                         docker compose run --rm \
                             -v $NEW_RELEASE_DIR:/opt/myapp \
@@ -87,9 +92,34 @@ jobs:
                         # Пересобираем контейнеры в фоне (если изменился Image) и перезапускаем
                         docker compose up -d --build --remove-orphans
 
+                        # Простой healthcheck
+                        if curl --silent --fail --head http://localhost/api/news/; then
 
-                        # Удаляем старые релизы
-                        cd $PROJECT_ROOT/releases
-                        ls -t | tail -n +4 | xargs -I {} rm -rf {}
 
-                        echo "Deployment finished!"
+                            echo "Success"
+
+                            # Удаляем старые релизы только при успехе
+                            cd $PROJECT_ROOT/releases
+                            ls -t | tail -n +4 | xargs -I {} rm -rf {}
+
+                        else
+                            echo "Sited Down Rolling back"
+
+                            if [ -z "$PREV_RELEASE_DIR" ]; then
+                                echo "Error no previoues releases"
+                                exit 1
+                            fi
+
+                            ln -sfn $PREV_RELEASE_DIR/docker $PROJECT_ROOT/docker
+                            ln -sfn $PREV_RELEASE_DIR/.env $PROJECT_ROOT/.env
+                            ln -sfn $PREV_RELEASE_DIR $PROJECT_ROOT/current
+
+                            cp $PREV_RELEASE_DIR/docker-compose.yml $PROJECT_ROOT/docker-compose.yml
+
+                            cd $PROJECT_ROOT
+                            docker compose up -d --build --remove-orphans
+
+                            echo "Rollback complete"
+
+                            exit 1
+                        fi
